version: "3.8"

services:
  api:
    build: .
    container_name: nest_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: nest_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 10072025minhduy
      MYSQL_DATABASE: LaiXeBachKhoaDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
