services:
  api:
    build: .
    container_name: nest_api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    command: >
      sh -c "yarn prisma generate &&
             yarn prisma migrate deploy &&
             yarn start:prod"

  mysql:
    image: mysql:8
    container_name: nest_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 10072025minhduy
      MYSQL_DATABASE: LaiXeBachKhoaDB
    ports:
      - "3306:3306"
